# -*- coding: utf-8 -*-
import json
import os

class LanguageManager:
    """Gestor de idiomas con soporte para múltiples lenguajes"""
    
    LANGUAGES = {
        'es': {
            'name': 'Español',
            'flag': '🇪🇸',
            'translations': {
                
                # Dashboard
                'dash_files': 'Archivos',
                'dash_lines': 'Líneas',
                'dash_size': 'Tamaño',
                'dash_files_by_ext': 'Archivos por Extensión',
                'dash_lines_by_lang': 'Líneas por Lenguaje',
                'dash_distribution': 'Distribución',
                'dash_lang': 'Lang',
                'dash_files_count': 'Archivos',
                'dash_lines_count': 'Líneas',
                'dash_size_label': 'Tamaño',
                'dash_todos_title': 'TODOs, FIXMEs y Errores de Sintaxis',
                'dash_scan_btn': 'Escanear',
                'dash_errors': 'Errores',
                'dash_todos': 'TODOs',
                'dash_fixmes': 'FIXMEs',
                'dash_results': 'Resultados',
                'dash_dupes_title': 'Código Duplicado en Archivos Seleccionados',
                'dash_dupes_btn': 'Buscar Duplicados',
                'dash_cases_found': 'Casos Encontrados',
                'dash_lines_dupes': 'Líneas Duplicadas',
                'dash_details': 'Detalles',
                'dash_top_lines': 'Top 10 — Más Líneas de Código',
                'dash_top_size': 'Top 10 — Mayor Tamaño',
                'dash_go': 'Ir',
                'dash_open_with': 'Abrir con...',
                'dash_searching_duplicates': 'Buscando código duplicado...',
                'dash_comparing': 'Comparando',
                'dash_no_data': 'No hay datos para mostrar',
                'dash_select_finding': 'Selecciona un hallazgo para abrir su archivo',
                'dash_col_type': 'Tipo',
                'dash_col_file': 'Archivo',
                'dash_col_line': 'Línea',
                'dash_col_message': 'Mensaje',
                'dash_scanning_code': 'Escaneando código...',
                'tab_stats': 'Estadísticas',
                'tab_todos': 'TODOs / Errores',
                'tab_dupes': 'Código Duplicado',
                'tab_metrics': 'Top Archivos',
                
                # Menú Archivo
                'menu_file': 'Archivo',
                'menu_open_folder': 'Abrir Carpeta...',
                'menu_recent_folders': 'Carpetas Recientes',
                'menu_exit': 'Salir',
                'menu_empty': '(vacío)',
                
                # Menú Ver
                'menu_view': 'Ver',
                'menu_refresh': 'Refrescar',
                'menu_preview': 'Vista',
                'menu_dashboard': 'Dashboard',
                
                # Menú Selección
                'menu_selection': 'Selección',
                'menu_clear_selection': 'Limpiar Selección',
                'menu_copy_selected': 'Copiar Seleccionados',
                
                # Menú Herramientas
                'menu_tools': 'Herramientas',
                'menu_search_files': 'Buscar Archivos...',
                'menu_generate_readme': 'Generar README...',
                'menu_scan_todos': 'Buscar TODOs',
                'menu_detect_duplicates': 'Detectar Duplicados',
                'menu_limpmax': 'LimpMax',
                
                # Menú Temas
                'menu_themes': 'Temas',
                
                # Menú Ayuda
                'menu_help': 'Ayuda',
                'menu_shortcuts': 'Atajos de Teclado',
                'menu_about': 'Acerca de',
                
                # Toolbar
                'btn_open': 'Abrir',
                'btn_refresh': 'Refrescar',
                'btn_search': 'Buscar',
                'btn_preview': 'Vista',
                'btn_copy': 'Copiar',
                'btn_export': 'Exportar',
                'btn_dashboard': 'Dashboard',
                'btn_readme': 'README',
                'btn_theme': 'Tema',
                'btn_language': 'Idioma',
                
                # Tooltips
                'tooltip_open': 'Abrir carpeta (Ctrl+O)',
                'tooltip_refresh': 'Refrescar árbol (F5)',
                'tooltip_search': 'Buscar archivos (Ctrl+F)',
                'tooltip_preview': 'Mostrar/Ocultar Vista previa (Ctrl+P)',
                'tooltip_copy': 'Copiar seleccionados (Ctrl+C)',
                'tooltip_export': 'Opciones de exportación',
                'tooltip_dashboard': 'Ver dashboard del proyecto',
                'tooltip_readme': 'Generar README.md',
                'tooltip_theme': 'Cambiar tema',
                'tooltip_language': 'Cambiar idioma',
                'tooltip_zoom_in': 'Acercar (Ctrl++)',
                'tooltip_zoom_out': 'Alejar (Ctrl+-)',
                'tooltip_zoom_reset': 'Restablecer zoom (Ctrl+0)',
                
                # Status Bar
                'status_files': 'Archivos',
                'status_selected': 'Seleccionados',
                'status_lines': 'Líneas',
                'status_size': 'Tamaño',
                'status_ready': 'Listo',
                'status_loading': 'Cargando',
                'status_refreshing': 'Refrescando',
                'status_copied': 'copiados al portapapeles',
                'status_cleared': 'Selección limpiada',
                'status_refreshed': 'Árbol refrescado',
                
                # Mensajes
                'msg_no_folder': 'Primero debes seleccionar una carpeta',
                'msg_no_selection': 'No hay archivos seleccionados',
                'msg_folder_loaded': 'Carpeta cargada',
                'msg_success': 'Éxito',
                'msg_error': 'Error',
                'msg_warning': 'Aviso',
                'msg_copied': 'archivos copiados',
                'msg_exported': 'Exportado a',
                'msg_cannot_export': 'No se pudo exportar el archivo',
                
                # Diálogos
                'dialog_select_folder': 'Seleccionar Carpeta',
                'dialog_save_file': 'Guardar Archivo',
                'dialog_folder_not_exist': 'La carpeta no existe',
                
                # Export
                'export_with_content': 'Copiar con contenido',
                'export_paths_only': 'Copiar solo rutas',
                'export_tree_structure': 'Copiar estructura árbol',
                'export_for_llm': 'Copiar para LLM',
                'export_save_file': 'Guardar en archivo...',
                
                # Búsqueda
                'search_title': 'Buscar Archivos',
                'search_label': 'Buscar:',
                'search_btn': 'Buscar',
                'search_case_sensitive': 'Sensible a mayúsculas',
                'search_extension_only': 'Solo extensión',
                'search_results': 'Resultados:',
                'search_no_results': 'No se encontraron resultados',
                'search_select_all': 'Marcar todos',
                'search_include_dirs': 'Incluir directorios',
                'search_clear': 'Limpiar',
                'search_close': 'Cerrar',
                'search_placeholder': 'Escribe para buscar archivos...',
                
                # Dashboard
                'dashboard_title': 'Dashboard del Proyecto',
                'dashboard_tab_stats': 'Estadísticas',
                'dashboard_tab_todos': 'TODOs/FIXMEs',
                'dashboard_tab_duplicates': 'Código Duplicado',
                'dashboard_tab_metrics': 'Métricas',
                
                # README Generator
                'readme_title': 'Generador de README',
                'readme_project_name': 'Nombre del proyecto:',
                'readme_description': 'Descripción:',
                'readme_author_github': 'Autor / GitHub',
                'readme_license': 'Licencia',
                'readme_sections': 'Secciones',
                'readme_badges': 'Badges',
                'readme_toc': 'Tabla de contenidos',
                'readme_structure': 'Estructura del proyecto',
                'readme_stats': 'Estadísticas',
                'readme_installation': 'Instalación',
                'readme_usage': 'Uso',
                'readme_contributing': 'Contribuir',
                'readme_license_section': 'Licencia',
                'readme_contact': 'Contacto',
                'readme_structure_options': 'Opciones de estructura',
                'readme_depth': 'Profundidad:',
                'readme_collapse_large': 'Colapsar carpetas con muchos archivos',
                'readme_threshold': 'Umbral:',
                'readme_files_label': 'archivos',
                'readme_generate_btn': 'Generar Vista previa',
                'readme_markdown_view': 'Markdown',
                'readme_rendered_view': 'Renderizado',
                'readme_save_btn': 'Guardar',
                'readme_configuration': 'Configuración',
                'readme_preview': 'Vista previa',
                'readme_copy': 'Copiar',
                'readme_default_project': 'Mi Proyecto',
                'readme_default_description': 'Descripción del proyecto',
                'readme_default_author': 'Tu Nombre',
                'readme_default_github': '@tu_usuario',
                'readme_badge_status': 'Estado',
                'readme_badge_license': 'Licencia',
                'readme_badge_stars': 'Estrellas',
                'readme_heading_toc': 'Tabla de Contenidos',
                'readme_heading_about': 'Sobre el Proyecto',
                'readme_heading_structure': 'Estructura del Proyecto',
                'readme_heading_stats': 'Estadísticas',
                'readme_heading_installation': 'Instalación',
                'readme_heading_usage': 'Uso',
                'readme_heading_contributing': 'Contribuir',
                'readme_heading_license': 'Licencia',
                'readme_heading_contact': 'Contacto',
                'readme_install_clone_repo': 'Clonar el repositorio',
                'readme_install_enter_directory': 'Entrar al directorio',
                'readme_install_dependencies': 'Instalar dependencias',
                'readme_install_add_command': 'Agregar comando de instalación',
                'readme_usage_add_instructions': 'Agregar instrucciones de uso',
                'readme_contrib_intro': 'Las contribuciones son bienvenidas. Por favor:',
                'readme_contrib_step_1': 'Fork el proyecto',
                'readme_contrib_step_2': 'Crea tu Feature Branch (`git checkout -b feature/AmazingFeature`)',
                'readme_contrib_step_3': "Commit tus cambios (`git commit -m 'Add some AmazingFeature'`)",
                'readme_contrib_step_4': 'Push al Branch (`git push origin feature/AmazingFeature`)',
                'readme_contrib_step_5': 'Abre un Pull Request',
                'readme_license_line': 'Distribuido bajo la licencia {license}. Ver `LICENSE` para más información.',
                'readme_contact_project_label': 'Proyecto',
                'readme_tree_no_folder': 'No hay carpeta seleccionada',
                'readme_stats_total_files': 'Total de archivos',
                'readme_stats_total_lines': 'Líneas de código',
                'readme_stats_total_size': 'Tamaño total',
                'readme_stats_top_languages': 'Lenguajes principales',
                'readme_stats_lines_label': 'Líneas',
                'readme_save_success_prefix': 'README guardado en',
                'readme_save_error_prefix': 'No se pudo guardar',
                'readme_copy_success': 'README copiado al portapapeles',
                
                # Contexto
                'context_mark': 'Marcar/Desmarcar',
                'context_copy_path': 'Copiar ruta',
                'context_open_location': 'Abrir ubicación',
                
                # Carpetas recientes
                'tooltip_recent': 'Carpetas recientes',
                'btn_recent': 'Recientes',
                'clear_history': 'Limpiar historial',
                'history_cleared': 'Historial limpiado',
                
                # Atajos de teclado
                'shortcuts_subtitle': 'Referencia rápida de atajos de teclado',
                'shortcuts_section_general': 'General',
                'shortcuts_section_selection': 'Selección',
                'shortcuts_section_navigation': 'Navegación',
                'shortcuts_section_zoom': 'Zoom',
                'shortcuts_section_tools': 'Herramientas',
                'shortcuts_exit': 'Salir de la aplicación',
                'shortcuts_refresh': 'Refrescar árbol de archivos',
                'shortcuts_mark': 'Marcar / Desmarcar archivo',
                'shortcuts_clear': 'Limpiar selección',
                'shortcuts_mark_file': 'Marcar archivo',
                'shortcuts_context': 'Abrir menú contextual',
                'shortcuts_zoom_scroll': 'Zoom con rueda del mouse',

                # Acerca de
                'about_description': 'Explorador de archivos profesional con análisis de código y métricas avanzadas.',
                'about_feat_selection': 'Selección inteligente de archivos',
                'about_feat_analysis': 'Análisis de código (TODOs, duplicados)',
                'about_feat_dashboard': 'Dashboard con métricas y gráficas',
                'about_feat_readme': 'Generador automático de README',
                'about_feat_themes': '5 temas profesionales',
                'about_feat_i18n': 'Soporte multiidioma',
                'about_feat_zoom': 'Zoom de código',
                'about_feat_export': 'Exportación en múltiples formatos',

                # Botones principales
                'btn_clear': 'Limpiar',
                'btn_todos': 'TD',
                'btn_duplicates': 'Duplicados',
                'btn_limpmax': 'LimpMax',
                'btn_shortcuts': 'Atajos',
                'btn_about': 'Acerca de',
                'tooltip_clear': 'Limpiar selección (Ctrl+D)',
                'tooltip_todos': 'Buscar TODOs y errores',
                'tooltip_duplicates': 'Detectar código duplicado',
                'tooltip_limpmax': 'Limpieza masiva de prints y comentarios',
                'tooltip_shortcuts': 'Atajos de teclado',
                'tooltip_about': 'Acerca de Code Tools ++',
                'limpmax_title': 'Limpieza Maxima',
                'limpmax_subtitle': 'Limpia prints y comentarios con control por lenguaje y salida segura.',
                'limpmax_source': 'Origen',
                'limpmax_options': 'Opciones',
                'limpmax_output': 'Salida',
                'limpmax_progress': 'Progreso y resultados',
                'limpmax_scope_all': 'Procesar carpeta completa',
                'limpmax_scope_single': 'Procesar un solo archivo',
                'limpmax_remove_prints': 'Eliminar prints / logs (Python, JS/TS, Java, C/C++, etc.)',
                'limpmax_remove_comments': 'Eliminar comentarios por lenguaje',
                'limpmax_remove_prints_label': 'Limpieza de logs',
                'limpmax_remove_comments_label': 'Limpieza de comentarios',
                'limpmax_output_mirror': 'Crear carpeta nueva (estructura espejo)',
                'limpmax_output_overwrite': 'Reemplazar archivos originales',
                'limpmax_pick_file': 'Seleccionar archivo',
                'limpmax_pick_output': 'Seleccionar carpeta de salida',
                'limpmax_eta': 'Tiempo restante',
                'limpmax_starting': 'Iniciando LimpMax...',
                'limpmax_done': 'Proceso finalizado',
                'limpmax_processed': 'Archivos procesados',
                'limpmax_copied': 'Archivos copiados',
                'limpmax_modified': 'Archivos modificados',
                'limpmax_prints_removed': 'Prints/Logs eliminados',
                'limpmax_comments_removed': 'Comentarios eliminados',
                'limpmax_unsupported': 'No compatibles',
                'limpmax_time': 'Tiempo total',
                'limpmax_err_project': 'Selecciona una carpeta de proyecto válida.',
                'limpmax_err_single': 'Selecciona un archivo válido.',
                'limpmax_err_option': 'Activa al menos una opción: prints o comentarios.',
                'limpmax_err_output': 'Selecciona una carpeta de salida.',
                'limpmax_err_same_output': 'La salida no puede ser la misma carpeta del proyecto.',

                # About Window
                'about_app_tagline': 'Análisis profesional de código · Exportación inteligente · Dashboard interactivo',
                'about_section_features': 'Características',
                'about_section_info': 'Información',
                'about_feature_files': 'Gestión\nde Archivos',
                'about_feature_files_desc': 'Árbol jerárquico\ncon selección múltiple',
                'about_feature_dashboard': 'Dashboard\nInteractivo',
                'about_feature_dashboard_desc': 'Gráficos y stats\nen tiempo real',
                'about_feature_search': 'Búsqueda\nAvanzada',
                'about_feature_search_desc': 'Filtros y regex\npoderosos',
                'about_feature_export': 'Exportación\nFlexible',
                'about_feature_export_desc': 'Markdown, TXT,\nClipboard, LLM',
                'about_feature_ai': 'Chat IA\nIntegrado',
                'about_feature_ai_desc': 'Asistencia de IA\ncon modelos dinámicos',
                'about_feature_limpmax': 'LimpMax\nInteligente',
                'about_feature_limpmax_desc': 'Limpieza masiva de\nprints y comentarios',
                'about_feature_readme': 'README\nAutomático',
                'about_feature_readme_desc': 'Generación\nprofesional',
                'about_feature_themes': 'Temas\nPersonalizables',
                'about_feature_themes_desc': '8+ temas\nprofesionales',
                'about_feature_todos': 'Análisis\nde TODOs',
                'about_feature_todos_desc': 'Escaneo de\ncomentarios',
                'about_feature_duplicates': 'Detección\nDuplicados',
                'about_feature_duplicates_desc': 'Archivos\nidénticos',
                'about_feature_i18n': 'Multi\nIdioma',
                'about_feature_i18n_desc': 'Español\ne Inglés',
                'about_info_details': 'Detalles',
                'about_info_contact': 'Contacto',
                'about_info_version': 'Versión',
                'about_info_developer': 'Desarrollador',
                'about_info_python': 'Python',
                'about_info_framework': 'Framework',
                'about_info_github': 'GitHub',
                'about_info_email': 'Email',
                'about_info_license': 'Licencia',
                'about_info_languages': 'Idiomas',
                
                # Theme Selector
                'theme_window_title': 'Apariencia',
                'theme_subtitle': 'Elige el esquema de color de la interfaz',
                'theme_active': 'Tema activo',
                'theme_badge_active': '• Activo',
                'theme_btn_apply': 'Aplicar',
                'theme_anim_title': 'Animaciones',
                'theme_anim_bar': 'Fondo animado barra principal',
                'theme_anim_enabled': 'Encendida',
                'theme_anim_disabled': 'Apagada',
                
                # Language Selector
                'lang_window_title': 'Idioma / Language',
                'lang_subtitle': 'Selecciona el idioma de la interfaz',
                'lang_active': 'Idioma activo',
                'lang_badge_active': '• Activo',
                'lang_btn_apply': 'Aplicar',
                
                # AI Chat
                'btn_ai': 'IA',
                'tooltip_ai': 'Chat con IA (Ctrl+I)',
                'menu_ai_chat': 'Chat con IA',
                'ai_chat_title': 'Chat con IA',
                'ai_send': 'Enviar',
                'ai_clear': 'Limpiar',
                'ai_analyze': 'Analizar Seleccionados',
                'ai_fix_errors': 'Corregir Errores',
                'ai_document': 'Documentar',
                'ai_optimize': 'Optimizar',
                'ai_explain': 'Explicar',
                'ai_placeholder': 'Escribe tu mensaje... (Shift+Enter para nueva línea)',
                'ai_thinking': 'Pensando...',
                'ai_no_files': 'No hay archivos seleccionados',
                'ai_error': 'Error al comunicarse con la IA',
                'ai_select_model': 'Modelos',
                'ai_add_custom_model': '➕ Agregar modelo personalizado...',
                'ai_model_changed': 'Modelo cambiado a:',
                'ai_select_model_subtitle': 'Selecciona un modelo para usar en el chat',
                'ai_model_active_badge': 'Activo',
                'ai_confirm': 'Confirmar',
                'ai_delete_model_confirm': "¿Eliminar el modelo '{name}'?",
                'ai_add_model_subtitle': 'Configura un modelo personalizado de OpenRouter',
                'ai_model_name_label': 'Nombre del modelo:',
                'ai_model_name_placeholder': 'Mi Modelo Custom',
                'ai_model_id_label': 'Model ID (ej: anthropic/claude-3-opus):',
                'ai_model_id_placeholder': 'anthropic/claude-3-opus',
                'ai_api_key_label': 'API Key de OpenRouter:',
                'ai_description_label': 'Descripción (opcional):',
                'ai_description_placeholder': 'Descripción corta',
                'ai_max_tokens_label': 'Máximo de tokens:',
                'ai_custom_logo_label': 'Logo personalizado (PNG/GIF):',
                'ai_select_logo_title': 'Seleccionar logo',
                'ai_image_filetypes': 'Imágenes',
                'ai_browse': 'Buscar',
                'ai_name_model_required': 'Nombre y Model ID son requeridos',
                'ai_add': 'Agregar',
                'ai_cancel': 'Cancelar',
            }
        },
        'en': {
            'name': 'English',
            'flag': '🇬🇧',
            'translations': {
                
                # Dashboard
                'dash_files': 'Files',
                'dash_lines': 'Lines',
                'dash_size': 'Size',
                'dash_files_by_ext': 'Files by Extension',
                'dash_lines_by_lang': 'Lines by Language',
                'dash_distribution': 'Distribution',
                'dash_lang': 'Lang',
                'dash_files_count': 'Files',
                'dash_lines_count': 'Lines',
                'dash_size_label': 'Size',
                'dash_todos_title': 'TODOs, FIXMEs and Syntax Errors',
                'dash_scan_btn': 'Scan',
                'dash_errors': 'Errors',
                'dash_todos': 'TODOs',
                'dash_fixmes': 'FIXMEs',
                'dash_results': 'Results',
                'dash_dupes_title': 'Duplicate Code in Selected Files',
                'dash_dupes_btn': 'Find Duplicates',
                'dash_cases_found': 'Cases Found',
                'dash_lines_dupes': 'Duplicate Lines',
                'dash_details': 'Details',
                'dash_top_lines': 'Top 10 — Most Lines of Code',
                'dash_top_size': 'Top 10 — Largest Size',
                'dash_go': 'Go',
                'dash_open_with': 'Open with...',
                'dash_searching_duplicates': 'Searching duplicate code...',
                'dash_comparing': 'Comparing',
                'dash_no_data': 'No data to display',
                'dash_select_finding': 'Select a finding to open its file',
                'dash_col_type': 'Type',
                'dash_col_file': 'File',
                'dash_col_line': 'Line',
                'dash_col_message': 'Message',
                'dash_scanning_code': 'Scanning code...',
                'tab_stats': 'Statistics',
                'tab_todos': 'TODOs / Errors',
                'tab_dupes': 'Duplicate Code',
                'tab_metrics': 'Top Files',
                
                # File Menu
                'menu_file': 'File',
                'menu_open_folder': 'Open Folder...',
                'menu_recent_folders': 'Recent Folders',
                'menu_exit': 'Exit',
                'menu_empty': '(empty)',
                
                # View Menu
                'menu_view': 'View',
                'menu_refresh': 'Refresh',
                'menu_preview': 'Preview',
                'menu_dashboard': 'Dashboard',
                
                # Selection Menu
                'menu_selection': 'Selection',
                'menu_clear_selection': 'Clear Selection',
                'menu_copy_selected': 'Copy Selected',
                
                # Tools Menu
                'menu_tools': 'Tools',
                'menu_search_files': 'Search Files...',
                'menu_generate_readme': 'Generate README...',
                'menu_scan_todos': 'Scan TODOs',
                'menu_detect_duplicates': 'Detect Duplicates',
                'menu_limpmax': 'CleanMax',
                
                # Themes Menu
                'menu_themes': 'Themes',
                
                # Help Menu
                'menu_help': 'Help',
                'menu_shortcuts': 'Keyboard Shortcuts',
                'menu_about': 'About',
                
                # Toolbar
                'btn_open': 'Open',
                'btn_refresh': 'Refresh',
                'btn_search': 'Search',
                'btn_preview': 'Preview',
                'btn_copy': 'Copy',
                'btn_export': 'Export',
                'btn_dashboard': 'Dashboard',
                'btn_readme': 'README',
                'btn_theme': 'Theme',
                'btn_language': 'Language',
                
                # Tooltips
                'tooltip_open': 'Open folder (Ctrl+O)',
                'tooltip_refresh': 'Refresh tree (F5)',
                'tooltip_search': 'Search files (Ctrl+F)',
                'tooltip_preview': 'Show/Hide preview (Ctrl+P)',
                'tooltip_copy': 'Copy selected (Ctrl+C)',
                'tooltip_export': 'Export options',
                'tooltip_dashboard': 'View project dashboard',
                'tooltip_readme': 'Generate README.md',
                'tooltip_theme': 'Change theme',
                'tooltip_language': 'Change language',
                'tooltip_zoom_in': 'Zoom in (Ctrl++)',
                'tooltip_zoom_out': 'Zoom out (Ctrl+-)',
                'tooltip_zoom_reset': 'Reset zoom (Ctrl+0)',
                
                # Status Bar
                'status_files': 'Files',
                'status_selected': 'Selected',
                'status_lines': 'Lines',
                'status_size': 'Size',
                'status_ready': 'Ready',
                'status_loading': 'Loading',
                'status_refreshing': 'Refreshing',
                'status_copied': 'copied to clipboard',
                'status_cleared': 'Selection cleared',
                'status_refreshed': 'Tree refreshed',
                
                # Messages
                'msg_no_folder': 'You must select a folder first',
                'msg_no_selection': 'No files selected',
                'msg_folder_loaded': 'Folder loaded',
                'msg_success': 'Success',
                'msg_error': 'Error',
                'msg_warning': 'Warning',
                'msg_copied': 'files copied',
                'msg_exported': 'Exported to',
                'msg_cannot_export': 'Could not export file',
                
                # Dialogs
                'dialog_select_folder': 'Select Folder',
                'dialog_save_file': 'Save File',
                'dialog_folder_not_exist': 'Folder does not exist',
                
                # Export
                'export_with_content': 'Copy with content',
                'export_paths_only': 'Copy paths only',
                'export_tree_structure': 'Copy tree structure',
                'export_for_llm': 'Copy for LLM',
                'export_save_file': 'Save to file...',
                
                # Search
                'search_title': 'Search Files',
                'search_label': 'Search:',
                'search_btn': 'Search',
                'search_case_sensitive': 'Case sensitive',
                'search_extension_only': 'Extension only',
                'search_results': 'Results:',
                'search_no_results': 'No results found',
                'search_select_all': 'Select all',
                'search_include_dirs': 'Include directories',
                'search_clear': 'Clear',
                'search_close': 'Close',
                'search_placeholder': 'Type to search files...',
                
                # Dashboard
                'dashboard_title': 'Project Dashboard',
                'dashboard_tab_stats': 'Statistics',
                'dashboard_tab_todos': 'TODOs/FIXMEs',
                'dashboard_tab_duplicates': 'Duplicate Code',
                'dashboard_tab_metrics': 'Metrics',
                
                # README Generator
                'readme_title': 'README Generator',
                'readme_project_name': 'Project name:',
                'readme_description': 'Description:',
                'readme_author_github': 'Author / GitHub',
                'readme_license': 'License',
                'readme_sections': 'Sections',
                'readme_badges': 'Badges',
                'readme_toc': 'Table of contents',
                'readme_structure': 'Project structure',
                'readme_stats': 'Statistics',
                'readme_installation': 'Installation',
                'readme_usage': 'Usage',
                'readme_contributing': 'Contributing',
                'readme_license_section': 'License',
                'readme_contact': 'Contact',
                'readme_structure_options': 'Structure options',
                'readme_depth': 'Depth:',
                'readme_collapse_large': 'Collapse large directories',
                'readme_threshold': 'Threshold:',
                'readme_files_label': 'files',
                'readme_generate_btn': 'Generate Preview',
                'readme_markdown_view': 'Markdown',
                'readme_rendered_view': 'Rendered',
                'readme_save_btn': 'Save',
                'readme_configuration': 'Configuration',
                'readme_preview': 'Preview',
                'readme_copy': 'Copy',
                'readme_default_project': 'My Project',
                'readme_default_description': 'Project description',
                'readme_default_author': 'Your Name',
                'readme_default_github': '@your_username',
                'readme_badge_status': 'Status',
                'readme_badge_license': 'License',
                'readme_badge_stars': 'Stars',
                'readme_heading_toc': 'Table of Contents',
                'readme_heading_about': 'About the Project',
                'readme_heading_structure': 'Project Structure',
                'readme_heading_stats': 'Statistics',
                'readme_heading_installation': 'Installation',
                'readme_heading_usage': 'Usage',
                'readme_heading_contributing': 'Contributing',
                'readme_heading_license': 'License',
                'readme_heading_contact': 'Contact',
                'readme_install_clone_repo': 'Clone the repository',
                'readme_install_enter_directory': 'Enter the directory',
                'readme_install_dependencies': 'Install dependencies',
                'readme_install_add_command': 'Add installation command',
                'readme_usage_add_instructions': 'Add usage instructions',
                'readme_contrib_intro': 'Contributions are welcome. Please:',
                'readme_contrib_step_1': 'Fork the project',
                'readme_contrib_step_2': 'Create your Feature Branch (`git checkout -b feature/AmazingFeature`)',
                'readme_contrib_step_3': "Commit your changes (`git commit -m 'Add some AmazingFeature'`)",
                'readme_contrib_step_4': 'Push to the Branch (`git push origin feature/AmazingFeature`)',
                'readme_contrib_step_5': 'Open a Pull Request',
                'readme_license_line': 'Distributed under the {license} license. See `LICENSE` for more information.',
                'readme_contact_project_label': 'Project',
                'readme_tree_no_folder': 'No folder selected',
                'readme_stats_total_files': 'Total files',
                'readme_stats_total_lines': 'Lines of code',
                'readme_stats_total_size': 'Total size',
                'readme_stats_top_languages': 'Top languages',
                'readme_stats_lines_label': 'lines',
                'readme_save_success_prefix': 'README saved to',
                'readme_save_error_prefix': 'Could not save',
                'readme_copy_success': 'README copied to clipboard',
                
                # Context
                'context_mark': 'Mark/Unmark',
                'context_copy_path': 'Copy path',
                'context_open_location': 'Open location',
                
                # Recent Folders
                'tooltip_recent': 'Recent folders',
                'btn_recent': 'Recent',
                'clear_history': 'Clear history',
                'history_cleared': 'History cleared',
                
                # Shortcuts window
                'shortcuts_subtitle': 'Quick keyboard shortcut reference',
                'shortcuts_section_general': 'General',
                'shortcuts_section_selection': 'Selection',
                'shortcuts_section_navigation': 'Navigation',
                'shortcuts_section_zoom': 'Zoom',
                'shortcuts_section_tools': 'Tools',
                'shortcuts_exit': 'Exit the application',
                'shortcuts_refresh': 'Refresh file tree',
                'shortcuts_mark': 'Mark / Unmark file',
                'shortcuts_clear': 'Clear selection',
                'shortcuts_mark_file': 'Mark file',
                'shortcuts_context': 'Open context menu',
                'shortcuts_zoom_scroll': 'Zoom with mouse scroll',

                # About window
                'about_description': 'Professional file explorer with code analysis and advanced metrics.',
                'about_feat_selection': 'Smart file selection',
                'about_feat_analysis': 'Code analysis (TODOs, duplicates)',
                'about_feat_dashboard': 'Dashboard with metrics and charts',
                'about_feat_readme': 'Automatic README generator',
                'about_feat_themes': '5 professional themes',
                'about_feat_i18n': 'Multi-language support',
                'about_feat_zoom': 'Code zoom functionality',
                'about_feat_export': 'Export in multiple formats',

                # Toolbar new buttons
                'btn_clear': 'Clear',
                'btn_todos': 'TD',
                'btn_duplicates': 'Duplicates',
                'btn_limpmax': 'CleanMax',
                'btn_shortcuts': 'Shortcuts',
                'btn_about': 'About',
                'tooltip_clear': 'Clear selection (Ctrl+D)',
                'tooltip_todos': 'Find TODOs and errors',
                'tooltip_duplicates': 'Detect duplicate code',
                'tooltip_limpmax': 'Mass clean prints and comments',
                'tooltip_shortcuts': 'Keyboard shortcuts',
                'tooltip_about': 'About Code Tools ++',
                'limpmax_title': 'CleanMax',
                'limpmax_subtitle': 'Remove prints and comments with language-aware safe processing.',
                'limpmax_source': 'Source',
                'limpmax_options': 'Options',
                'limpmax_output': 'Output',
                'limpmax_progress': 'Progress and results',
                'limpmax_scope_all': 'Process full folder',
                'limpmax_scope_single': 'Process single file',
                'limpmax_remove_prints': 'Remove prints / logs (Python, JS/TS, Java, C/C++, etc.)',
                'limpmax_remove_comments': 'Remove comments by language',
                'limpmax_remove_prints_label': 'Log cleanup',
                'limpmax_remove_comments_label': 'Comment cleanup',
                'limpmax_output_mirror': 'Create new mirror folder',
                'limpmax_output_overwrite': 'Overwrite original files',
                'limpmax_pick_file': 'Select file',
                'limpmax_pick_output': 'Select output folder',
                'limpmax_eta': 'Time remaining',
                'limpmax_starting': 'Starting LimpMax...',
                'limpmax_done': 'Process finished',
                'limpmax_processed': 'Processed files',
                'limpmax_copied': 'Copied files',
                'limpmax_modified': 'Modified files',
                'limpmax_prints_removed': 'Removed prints/logs',
                'limpmax_comments_removed': 'Removed comments',
                'limpmax_unsupported': 'Unsupported',
                'limpmax_time': 'Total time',
                'limpmax_err_project': 'Select a valid project folder.',
                'limpmax_err_single': 'Select a valid file.',
                'limpmax_err_option': 'Enable at least one option: prints or comments.',
                'limpmax_err_output': 'Select an output folder.',
                'limpmax_err_same_output': 'Output folder must be different from project folder.',

                # About Window
                'about_app_tagline': 'Professional code analysis · Smart export · Interactive dashboard',
                'about_section_features': 'Features',
                'about_section_info': 'Information',
                'about_feature_files': 'File\nManagement',
                'about_feature_files_desc': 'Hierarchical tree\nwith multi-select',
                'about_feature_dashboard': 'Interactive\nDashboard',
                'about_feature_dashboard_desc': 'Real-time charts\nand statistics',
                'about_feature_search': 'Advanced\nSearch',
                'about_feature_search_desc': 'Powerful filters\nand regex',
                'about_feature_export': 'Flexible\nExport',
                'about_feature_export_desc': 'Markdown, TXT,\nClipboard, LLM',
                'about_feature_ai': 'Integrated\nAI Chat',
                'about_feature_ai_desc': 'AI assistance with\ndynamic models',
                'about_feature_limpmax': 'Smart\nLimpMax',
                'about_feature_limpmax_desc': 'Bulk cleanup of\nprints and comments',
                'about_feature_readme': 'Automatic\nREADME',
                'about_feature_readme_desc': 'Professional\ngeneration',
                'about_feature_themes': 'Customizable\nThemes',
                'about_feature_themes_desc': '8+ professional\nthemes',
                'about_feature_todos': 'TODO\nAnalysis',
                'about_feature_todos_desc': 'Comment\nscanning',
                'about_feature_duplicates': 'Duplicate\nDetection',
                'about_feature_duplicates_desc': 'Identical\nfiles',
                'about_feature_i18n': 'Multi\nLanguage',
                'about_feature_i18n_desc': 'Spanish\nand English',
                'about_info_details': 'Details',
                'about_info_contact': 'Contact',
                'about_info_version': 'Version',
                'about_info_developer': 'Developer',
                'about_info_python': 'Python',
                'about_info_framework': 'Framework',
                'about_info_github': 'GitHub',
                'about_info_email': 'Email',
                'about_info_license': 'License',
                'about_info_languages': 'Languages',
                
                # Theme Selector
                'theme_window_title': 'Appearance',
                'theme_subtitle': 'Choose the interface color scheme',
                'theme_active': 'Active theme',
                'theme_badge_active': '• Active',
                'theme_btn_apply': 'Apply',
                'theme_anim_title': 'Animations',
                'theme_anim_bar': 'Main toolbar animated background',
                'theme_anim_enabled': 'Enabled',
                'theme_anim_disabled': 'Disabled',
                
                # Language Selector
                'lang_window_title': 'Language / Idioma',
                'lang_subtitle': 'Select the interface language',
                'lang_active': 'Active language',
                'lang_badge_active': '• Active',
                'lang_btn_apply': 'Apply',
                
                # AI Chat
                'btn_ai': 'AI',
                'tooltip_ai': 'AI Chat (Ctrl+I)',
                'menu_ai_chat': 'AI Chat',
                'ai_chat_title': 'AI Chat',
                'ai_send': 'Send',
                'ai_clear': 'Clear',
                'ai_analyze': 'Analyze Selected',
                'ai_fix_errors': 'Fix Errors',
                'ai_document': 'Document',
                'ai_optimize': 'Optimize',
                'ai_explain': 'Explain',
                'ai_placeholder': 'Type your message... (Shift+Enter for new line)',
                'ai_thinking': 'Thinking...',
                'ai_no_files': 'No files selected',
                'ai_error': 'Error communicating with AI',
                'ai_select_model': 'Models',
                'ai_add_custom_model': '➕ Add custom model...',
                'ai_model_changed': 'Model changed to:',
                'ai_select_model_subtitle': 'Select a model to use in the chat',
                'ai_model_active_badge': 'Active',
                'ai_confirm': 'Confirm',
                'ai_delete_model_confirm': "Delete model '{name}'?",
                'ai_add_model_subtitle': 'Configure a custom OpenRouter model',
                'ai_model_name_label': 'Model name:',
                'ai_model_name_placeholder': 'My Custom Model',
                'ai_model_id_label': 'Model ID (e.g., anthropic/claude-3-opus):',
                'ai_model_id_placeholder': 'anthropic/claude-3-opus',
                'ai_api_key_label': 'OpenRouter API Key:',
                'ai_description_label': 'Description (optional):',
                'ai_description_placeholder': 'Short description',
                'ai_max_tokens_label': 'Maximum tokens:',
                'ai_custom_logo_label': 'Custom logo (PNG/GIF):',
                'ai_select_logo_title': 'Select logo',
                'ai_image_filetypes': 'Images',
                'ai_browse': 'Browse',
                'ai_name_model_required': 'Name and Model ID are required',
                'ai_add': 'Add',
                'ai_cancel': 'Cancel',
            }
        },
        'zh': {
            'name': '中文',
            'flag': '🇨🇳',
            'translations': {
                
                # Dashboard
                'dash_files': '文件',
                'dash_lines': '行数',
                'dash_size': '大小',
                'dash_files_by_ext': '按扩展名分类文件',
                'dash_lines_by_lang': '按语言分类行数',
                'dash_distribution': '分布',
                'dash_lang': '语言',
                'dash_files_count': '文件',
                'dash_lines_count': '行数',
                'dash_size_label': '大小',
                'dash_todos_title': '待办事项、待修复项和语法错误',
                'dash_scan_btn': '扫描',
                'dash_errors': '错误',
                'dash_todos': '待办事项',
                'dash_fixmes': '待修复项',
                'dash_results': '结果',
                'dash_dupes_title': '选定文件中的重复代码',
                'dash_dupes_btn': '查找重复',
                'dash_cases_found': '发现案例',
                'dash_lines_dupes': '重复行',
                'dash_details': '详情',
                'dash_top_lines': 'Top 10 — 代码行数最多',
                'dash_top_size': 'Top 10 — 文件最大',
                'dash_go': '前往',
                'dash_open_with': '打开方式...',
                'dash_searching_duplicates': '正在查找重复代码...',
                'dash_comparing': '正在比较',
                'dash_no_data': '暂无可显示的数据',
                'dash_select_finding': '选择一条结果以打开对应文件',
                'dash_col_type': '类型',
                'dash_col_file': '文件',
                'dash_col_line': '行',
                'dash_col_message': '消息',
                'dash_scanning_code': '正在扫描代码...',
                'tab_stats': '统计',
                'tab_todos': '待办事项 / 错误',
                'tab_dupes': '重复代码',
                'tab_metrics': '热门文件',
                
                # File Menu
                'menu_file': '文件',
                'menu_open_folder': '打开文件夹...',
                'menu_recent_folders': '最近的文件夹',
                'menu_exit': '退出',
                'menu_empty': '(空)',
                
                # View Menu
                'menu_view': '查看',
                'menu_refresh': '刷新',
                'menu_preview': '预览',
                'menu_dashboard': '仪表板',
                
                # Selection Menu
                'menu_selection': '选择',
                'menu_clear_selection': '清除选择',
                'menu_copy_selected': '复制已选',
                
                # Tools Menu
                'menu_tools': '工具',
                'menu_search_files': '搜索文件...',
                'menu_generate_readme': '生成 README...',
                'menu_scan_todos': '扫描待办事项',
                'menu_detect_duplicates': '检测重复',
                'menu_limpmax': '净码',
                
                # Themes Menu
                'menu_themes': '主题',
                
                # Help Menu
                'menu_help': '帮助',
                'menu_shortcuts': '键盘快捷键',
                'menu_about': '关于',
                
                # Toolbar
                'btn_open': '打开',
                'btn_refresh': '刷新',
                'btn_search': '搜索',
                'btn_preview': '预览',
                'btn_copy': '复制',
                'btn_export': '导出',
                'btn_dashboard': '仪表板',
                'btn_readme': '自述文件',
                'btn_theme': '主题',
                'btn_language': '语言',
                
                # Tooltips
                'tooltip_open': '打开文件夹 (Ctrl+O)',
                'tooltip_refresh': '刷新树 (F5)',
                'tooltip_search': '搜索文件 (Ctrl+F)',
                'tooltip_preview': '显示/隐藏预览 (Ctrl+P)',
                'tooltip_copy': '复制已选 (Ctrl+C)',
                'tooltip_export': '导出选项',
                'tooltip_dashboard': '查看项目仪表板',
                'tooltip_readme': '生成 README.md',
                'tooltip_theme': '更改主题',
                'tooltip_language': '更改语言',
                'tooltip_zoom_in': '放大 (Ctrl++)',
                'tooltip_zoom_out': '缩小 (Ctrl+-)',
                'tooltip_zoom_reset': '重置缩放 (Ctrl+0)',
                
                # Status Bar
                'status_files': '文件',
                'status_selected': '已选',
                'status_lines': '行数',
                'status_size': '大小',
                'status_ready': '就绪',
                'status_loading': '加载中',
                'status_refreshing': '刷新中',
                'status_copied': '已复制到剪贴板',
                'status_cleared': '已清除选择',
                'status_refreshed': '树已刷新',
                
                # Messages
                'msg_no_folder': '您必须先选择一个文件夹',
                'msg_no_selection': '未选择文件',
                'msg_folder_loaded': '文件夹已加载',
                'msg_success': '成功',
                'msg_error': '错误',
                'msg_warning': '警告',
                'msg_copied': '个文件已复制',
                'msg_exported': '已导出到',
                'msg_cannot_export': '无法导出文件',
                
                # Dialogs
                'dialog_select_folder': '选择文件夹',
                'dialog_save_file': '保存文件',
                'dialog_folder_not_exist': '文件夹不存在',
                
                # Export
                'export_with_content': '复制包含内容',
                'export_paths_only': '仅复制路径',
                'export_tree_structure': '复制树结构',
                'export_for_llm': '为 LLM 复制',
                'export_save_file': '保存到文件...',
                
                # Search
                'search_title': '搜索文件',
                'search_label': '搜索:',
                'search_btn': '搜索',
                'search_case_sensitive': '区分大小写',
                'search_extension_only': '仅扩展名',
                'search_results': '结果:',
                'search_no_results': '未找到结果',
                'search_select_all': '全选',
                'search_include_dirs': '包含目录',
                'search_clear': '清除',
                'search_close': '关闭',
                'search_placeholder': '输入以搜索文件...',
                
                # Dashboard
                'dashboard_title': '项目仪表板',
                'dashboard_tab_stats': '统计',
                'dashboard_tab_todos': 'TODOs/FIXMEs',
                'dashboard_tab_duplicates': '重复代码',
                'dashboard_tab_metrics': '指标',
                
                # README Generator
                'readme_title': 'README 生成器',
                'readme_project_name': '项目名称:',
                'readme_description': '描述:',
                'readme_author_github': '作者 / GitHub',
                'readme_license': '许可证',
                'readme_sections': '部分',
                'readme_badges': '徽章',
                'readme_toc': '目录',
                'readme_structure': '项目结构',
                'readme_stats': '统计',
                'readme_installation': '安装',
                'readme_usage': '使用',
                'readme_contributing': '贡献',
                'readme_license_section': '许可证',
                'readme_contact': '联系方式',
                'readme_structure_options': '结构选项',
                'readme_depth': '深度:',
                'readme_collapse_large': '折叠大目录',
                'readme_threshold': '阈值:',
                'readme_files_label': '个文件',
                'readme_generate_btn': '生成预览',
                'readme_markdown_view': 'Markdown',
                'readme_rendered_view': '渲染',
                'readme_save_btn': '保存',
                'readme_configuration': '配置',
                'readme_preview': '预览',
                'readme_copy': '复制',
                'readme_default_project': '我的项目',
                'readme_default_description': '项目描述',
                'readme_default_author': '你的名字',
                'readme_default_github': '@你的用户名',
                'readme_badge_status': '状态',
                'readme_badge_license': '许可证',
                'readme_badge_stars': '星标',
                'readme_heading_toc': '目录',
                'readme_heading_about': '关于项目',
                'readme_heading_structure': '项目结构',
                'readme_heading_stats': '统计',
                'readme_heading_installation': '安装',
                'readme_heading_usage': '使用',
                'readme_heading_contributing': '贡献',
                'readme_heading_license': '许可证',
                'readme_heading_contact': '联系方式',
                'readme_install_clone_repo': '克隆仓库',
                'readme_install_enter_directory': '进入目录',
                'readme_install_dependencies': '安装依赖',
                'readme_install_add_command': '添加安装命令',
                'readme_usage_add_instructions': '添加使用说明',
                'readme_contrib_intro': '欢迎贡献。请按以下步骤：',
                'readme_contrib_step_1': 'Fork 本项目',
                'readme_contrib_step_2': '创建功能分支 (`git checkout -b feature/AmazingFeature`)',
                'readme_contrib_step_3': "提交更改 (`git commit -m 'Add some AmazingFeature'`)",
                'readme_contrib_step_4': '推送分支 (`git push origin feature/AmazingFeature`)',
                'readme_contrib_step_5': '创建 Pull Request',
                'readme_license_line': '基于 {license} 许可证分发。更多信息请查看 `LICENSE`。',
                'readme_contact_project_label': '项目',
                'readme_tree_no_folder': '未选择文件夹',
                'readme_stats_total_files': '文件总数',
                'readme_stats_total_lines': '代码行数',
                'readme_stats_total_size': '总大小',
                'readme_stats_top_languages': '主要语言',
                'readme_stats_lines_label': '行',
                'readme_save_success_prefix': 'README 已保存到',
                'readme_save_error_prefix': '无法保存',
                'readme_copy_success': 'README 已复制到剪贴板',
                
                # Context
                'context_mark': '标记/取消标记',
                'context_copy_path': '复制路径',
                'context_open_location': '打开位置',
                
                # Recent Folders
                'tooltip_recent': '最近的文件夹',
                'btn_recent': '最近',
                'clear_history': '清除历史',
                'history_cleared': '历史已清除',
                
                # Shortcuts window
                'shortcuts_subtitle': '键盘快捷键快速参考',
                'shortcuts_section_general': '常规',
                'shortcuts_section_selection': '选择',
                'shortcuts_section_navigation': '导航',
                'shortcuts_section_zoom': '缩放',
                'shortcuts_section_tools': '工具',
                'shortcuts_exit': '退出应用程序',
                'shortcuts_refresh': '刷新文件树',
                'shortcuts_mark': '标记 / 取消标记文件',
                'shortcuts_clear': '清除选择',
                'shortcuts_mark_file': '标记文件',
                'shortcuts_context': '打开右键菜单',
                'shortcuts_zoom_scroll': '鼠标滚轮缩放',

                # About window
                'about_description': '专业文件浏览器，具有代码分析和高级指标功能。',
                'about_feat_selection': '智能文件选择',
                'about_feat_analysis': '代码分析（待办事项，重复）',
                'about_feat_dashboard': '带指标和图表的仪表板',
                'about_feat_readme': '自动 README 生成器',
                'about_feat_themes': '5 个专业主题',
                'about_feat_i18n': '多语言支持',
                'about_feat_zoom': '代码缩放功能',
                'about_feat_export': '多格式导出',

                # Toolbar new buttons
                'btn_clear': '清除',
                'btn_todos': '待办',
                'btn_duplicates': '重复',
                'btn_limpmax': '净码',
                'btn_shortcuts': '快捷键',
                'btn_about': '关于',
                'tooltip_clear': '清除选择 (Ctrl+D)',
                'tooltip_todos': '查找待办事项和错误',
                'tooltip_duplicates': '检测重复代码',
                'tooltip_limpmax': '批量清理 prints 与注释',
                'tooltip_shortcuts': '键盘快捷键',
                'tooltip_about': '关于 Code Tools ++',
                'limpmax_title': '净码',
                'limpmax_subtitle': '按语言安全清理 prints 和注释。',
                'limpmax_source': '来源',
                'limpmax_options': '选项',
                'limpmax_output': '输出',
                'limpmax_progress': '进度与结果',
                'limpmax_scope_all': '处理整个文件夹',
                'limpmax_scope_single': '只处理单个文件',
                'limpmax_remove_prints': '移除 prints / logs（Python, JS/TS, Java, C/C++ 等）',
                'limpmax_remove_comments': '按语言移除注释',
                'limpmax_remove_prints_label': '日志清理',
                'limpmax_remove_comments_label': '注释清理',
                'limpmax_output_mirror': '创建镜像输出文件夹',
                'limpmax_output_overwrite': '覆盖原始文件',
                'limpmax_pick_file': '选择文件',
                'limpmax_pick_output': '选择输出文件夹',
                'limpmax_eta': '剩余时间',
                'limpmax_starting': '正在启动 LimpMax...',
                'limpmax_done': '处理完成',
                'limpmax_processed': '已处理文件',
                'limpmax_copied': '已复制文件',
                'limpmax_modified': '已修改文件',
                'limpmax_prints_removed': '已移除 prints/logs',
                'limpmax_comments_removed': '已移除注释',
                'limpmax_unsupported': '不支持',
                'limpmax_time': '总耗时',
                'limpmax_err_project': '请选择有效的项目文件夹。',
                'limpmax_err_single': '请选择有效的文件。',
                'limpmax_err_option': '至少启用一个选项：prints 或注释。',
                'limpmax_err_output': '请选择输出文件夹。',
                'limpmax_err_same_output': '输出文件夹不能与项目文件夹相同。',

                # About Window
                'about_app_tagline': '专业代码分析 · 智能导出 · 交互式仪表板',
                'about_section_features': '特性',
                'about_section_info': '信息',
                'about_feature_files': '文件\n管理',
                'about_feature_files_desc': '多选分层\n树形结构',
                'about_feature_dashboard': '交互式\n仪表板',
                'about_feature_dashboard_desc': '实时图表\n和统计',
                'about_feature_search': '高级\n搜索',
                'about_feature_search_desc': '强大过滤\n和正则',
                'about_feature_export': '灵活\n导出',
                'about_feature_export_desc': 'Markdown, TXT,\n剪贴板, LLM',
                'about_feature_ai': '集成\nAI 聊天',
                'about_feature_ai_desc': '支持动态模型的\nAI 助手',
                'about_feature_limpmax': '智能\n净码',
                'about_feature_limpmax_desc': '批量清理 prints\n与注释',
                'about_feature_readme': '自动\nREADME',
                'about_feature_readme_desc': '专业\n生成',
                'about_feature_themes': '可定制\n主题',
                'about_feature_themes_desc': '8+ 专业\n主题',
                'about_feature_todos': '待办事项\n分析',
                'about_feature_todos_desc': '注释\n扫描',
                'about_feature_duplicates': '重复\n检测',
                'about_feature_duplicates_desc': '相同\n文件',
                'about_feature_i18n': '多\n语言',
                'about_feature_i18n_desc': '中文\n和英文',
                'about_info_details': '详情',
                'about_info_contact': '联系方式',
                'about_info_version': '版本',
                'about_info_developer': '开发者',
                'about_info_python': 'Python',
                'about_info_framework': '框架',
                'about_info_github': 'GitHub',
                'about_info_email': '电子邮件',
                'about_info_license': '许可证',
                'about_info_languages': '语言',
                
                # Theme Selector
                'theme_window_title': '外观',
                'theme_subtitle': '选择界面配色方案',
                'theme_active': '活动主题',
                'theme_badge_active': '• 活动',
                'theme_btn_apply': '应用',
                'theme_anim_title': '动画',
                'theme_anim_bar': '主工具栏动态背景',
                'theme_anim_enabled': '已启用',
                'theme_anim_disabled': '已禁用',
                
                # Language Selector
                'lang_window_title': '语言 / Language',
                'lang_subtitle': '选择界面语言',
                'lang_active': '活动语言',
                'lang_badge_active': '• 活动',
                'lang_btn_apply': '应用',
                
                # AI Chat
                'btn_ai': '智能',
                'tooltip_ai': 'AI 聊天 (Ctrl+I)',
                'menu_ai_chat': 'AI 聊天',
                'ai_chat_title': 'AI 聊天',
                'ai_send': '发送',
                'ai_clear': '清除',
                'ai_analyze': '分析选中',
                'ai_fix_errors': '修复错误',
                'ai_document': '文档',
                'ai_optimize': '优化',
                'ai_explain': '解释',
                'ai_placeholder': '输入消息... (Shift+Enter 换行)',
                'ai_thinking': '思考中...',
                'ai_no_files': '未选择文件',
                'ai_error': '与AI通信错误',
                'ai_select_model': '模型',
                'ai_add_custom_model': '➕ 添加自定义模型...',
                'ai_model_changed': '模型已更改为:',
                'ai_select_model_subtitle': '选择要在聊天中使用的模型',
                'ai_model_active_badge': '已启用',
                'ai_confirm': '确认',
                'ai_delete_model_confirm': "删除模型 '{name}'？",
                'ai_add_model_subtitle': '配置自定义 OpenRouter 模型',
                'ai_model_name_label': '模型名称:',
                'ai_model_name_placeholder': '我的自定义模型',
                'ai_model_id_label': 'Model ID（例如 anthropic/claude-3-opus）:',
                'ai_model_id_placeholder': 'anthropic/claude-3-opus',
                'ai_api_key_label': 'OpenRouter API Key:',
                'ai_description_label': '描述（可选）:',
                'ai_description_placeholder': '简短描述',
                'ai_max_tokens_label': '最大 tokens:',
                'ai_custom_logo_label': '自定义 Logo（PNG/GIF）:',
                'ai_select_logo_title': '选择 Logo',
                'ai_image_filetypes': '图像',
                'ai_browse': '浏览',
                'ai_name_model_required': '模型名称和 Model ID 为必填',
                'ai_add': '添加',
                'ai_cancel': '取消',
            }
        },
        'ru': {
            'name': 'Русский',
            'flag': '🇷🇺',
            'translations': {
                
                # Dashboard
                'dash_files': 'Файлы',
                'dash_lines': 'Строки',
                'dash_size': 'Размер',
                'dash_files_by_ext': 'Файлы по расширениям',
                'dash_lines_by_lang': 'Строки по языкам',
                'dash_distribution': 'Распределение',
                'dash_lang': 'Язык',
                'dash_files_count': 'Файлы',
                'dash_lines_count': 'Строки',
                'dash_size_label': 'Размер',
                'dash_todos_title': 'ЗД, Исправить и синтаксические ошибки',
                'dash_scan_btn': 'Сканировать',
                'dash_errors': 'Ошибки',
                'dash_todos': 'ЗД',
                'dash_fixmes': 'Исправить',
                'dash_results': 'Результаты',
                'dash_dupes_title': 'Дублированный код в выбранных файлах',
                'dash_dupes_btn': 'Найти дубликаты',
                'dash_cases_found': 'Найдено случаев',
                'dash_lines_dupes': 'Дублированные строки',
                'dash_details': 'Детали',
                'dash_top_lines': 'Топ 10 — Больше строк кода',
                'dash_top_size': 'Топ 10 — Больший размер',
                'dash_go': 'Перейти',
                'dash_open_with': 'Открыть в...',
                'dash_searching_duplicates': 'Поиск дублированного кода...',
                'dash_comparing': 'Сравнение',
                'dash_no_data': 'Нет данных для отображения',
                'dash_select_finding': 'Выберите находку, чтобы открыть файл',
                'dash_col_type': 'Тип',
                'dash_col_file': 'Файл',
                'dash_col_line': 'Строка',
                'dash_col_message': 'Сообщение',
                'dash_scanning_code': 'Сканирование кода...',
                'tab_stats': 'Статистика',
                'tab_todos': 'TODO / Ошибки',
                'tab_dupes': 'Дублированный код',
                'tab_metrics': 'Топ файлов',
                
                # Меню Файл
                'menu_file': 'Файл',
                'menu_open_folder': 'Открыть папку...',
                'menu_recent_folders': 'Недавние папки',
                'menu_exit': 'Выход',
                'menu_empty': '(пусто)',
                
                # Меню Вид
                'menu_view': 'Вид',
                'menu_refresh': 'Обновить',
                'menu_preview': 'Просмотр',
                'menu_dashboard': 'Панель управления',
                
                # Меню Выбор
                'menu_selection': 'Выбор',
                'menu_clear_selection': 'Очистить выбор',
                'menu_copy_selected': 'Копировать выбранные',
                
                # Меню Инструменты
                'menu_tools': 'Инструменты',
                'menu_search_files': 'Поиск файлов...',
                'menu_generate_readme': 'Создать README...',
                'menu_scan_todos': 'Найти TODO',
                'menu_detect_duplicates': 'Найти дубликаты',
                'menu_limpmax': 'LimpMax',
                
                # Меню Темы
                'menu_themes': 'Темы',
                
                # Меню Помощь
                'menu_help': 'Помощь',
                'menu_shortcuts': 'Горячие клавиши',
                'menu_about': 'О программе',
                
                # Панель инструментов
                'btn_open': 'Открыть',
                'btn_refresh': 'Обновить',
                'btn_search': 'Поиск',
                'btn_preview': 'Просмотр',
                'btn_copy': 'Копировать',
                'btn_export': 'Экспорт',
                'btn_dashboard': 'Панель',
                'btn_readme': 'Описание',
                'btn_theme': 'Тема',
                'btn_language': 'Язык',
                
                # Подсказки
                'tooltip_open': 'Открыть папку (Ctrl+O)',
                'tooltip_refresh': 'Обновить дерево (F5)',
                'tooltip_search': 'Поиск файлов (Ctrl+F)',
                'tooltip_preview': 'Показать/скрыть просмотр (Ctrl+P)',
                'tooltip_copy': 'Копировать выбранные (Ctrl+C)',
                'tooltip_export': 'Параметры экспорта',
                'tooltip_dashboard': 'Показать панель проекта',
                'tooltip_readme': 'Создать README.md',
                'tooltip_theme': 'Изменить тему',
                'tooltip_language': 'Изменить язык',
                'tooltip_zoom_in': 'Увеличить (Ctrl++)',
                'tooltip_zoom_out': 'Уменьшить (Ctrl+-)',
                'tooltip_zoom_reset': 'Сбросить масштаб (Ctrl+0)',
                
                # Строка состояния
                'status_files': 'Файлы',
                'status_selected': 'Выбрано',
                'status_lines': 'Строки',
                'status_size': 'Размер',
                'status_ready': 'Готово',
                'status_loading': 'Загрузка',
                'status_refreshing': 'Обновление',
                'status_copied': 'скопировано в буфер обмена',
                'status_cleared': 'Выбор очищен',
                'status_refreshed': 'Дерево обновлено',
                
                # Сообщения
                'msg_no_folder': 'Сначала выберите папку',
                'msg_no_selection': 'Нет выбранных файлов',
                'msg_folder_loaded': 'Папка загружена',
                'msg_success': 'Успех',
                'msg_error': 'Ошибка',
                'msg_warning': 'Предупреждение',
                'msg_copied': 'файлов скопировано',
                'msg_exported': 'Экспортировано в',
                'msg_cannot_export': 'Не удалось экспортировать файл',
                
                # Диалоги
                'dialog_select_folder': 'Выбрать папку',
                'dialog_save_file': 'Сохранить файл',
                'dialog_folder_not_exist': 'Папка не существует',
                
                # Экспорт
                'export_with_content': 'Копировать с содержимым',
                'export_paths_only': 'Копировать только пути',
                'export_tree_structure': 'Копировать структуру дерева',
                'export_for_llm': 'Копировать для LLM',
                'export_save_file': 'Сохранить в файл...',
                
                # Поиск
                'search_title': 'Поиск файлов',
                'search_label': 'Поиск:',
                'search_btn': 'Искать',
                'search_case_sensitive': 'Учитывать регистр',
                'search_extension_only': 'Только расширение',
                'search_results': 'Результаты:',
                'search_no_results': 'Результатов не найдено',
                'search_select_all': 'Выбрать все',
                'search_include_dirs': 'Включить папки',
                'search_clear': 'Очистить',
                'search_close': 'Закрыть',
                'search_placeholder': 'Введите для поиска файлов...',
                
                # Панель управления
                'dashboard_title': 'Панель проекта',
                'dashboard_tab_stats': 'Статистика',
                'dashboard_tab_todos': 'TODO/FIXME',
                'dashboard_tab_duplicates': 'Дублированный код',
                'dashboard_tab_metrics': 'Метрики',
                
                # Генератор README
                'readme_title': 'Генератор README',
                'readme_project_name': 'Название проекта:',
                'readme_description': 'Описание:',
                'readme_author_github': 'Автор / GitHub',
                'readme_license': 'Лицензия',
                'readme_sections': 'Разделы',
                'readme_badges': 'Значки',
                'readme_toc': 'Оглавление',
                'readme_structure': 'Структура проекта',
                'readme_stats': 'Статистика',
                'readme_installation': 'Установка',
                'readme_usage': 'Использование',
                'readme_contributing': 'Участие',
                'readme_license_section': 'Лицензия',
                'readme_contact': 'Контакты',
                'readme_structure_options': 'Параметры структуры',
                'readme_depth': 'Глубина:',
                'readme_collapse_large': 'Свернуть большие папки',
                'readme_threshold': 'Порог:',
                'readme_files_label': 'файлов',
                'readme_generate_btn': 'Создать просмотр',
                'readme_markdown_view': 'Markdown',
                'readme_rendered_view': 'Отрендеренный',
                'readme_save_btn': 'Сохранить',
                'readme_configuration': 'Конфигурация',
                'readme_preview': 'Просмотр',
                'readme_copy': 'Копировать',
                'readme_default_project': 'Мой проект',
                'readme_default_description': 'Описание проекта',
                'readme_default_author': 'Ваше имя',
                'readme_default_github': '@ваш_пользователь',
                'readme_badge_status': 'Статус',
                'readme_badge_license': 'Лицензия',
                'readme_badge_stars': 'Звезды',
                'readme_heading_toc': 'Оглавление',
                'readme_heading_about': 'О проекте',
                'readme_heading_structure': 'Структура проекта',
                'readme_heading_stats': 'Статистика',
                'readme_heading_installation': 'Установка',
                'readme_heading_usage': 'Использование',
                'readme_heading_contributing': 'Участие',
                'readme_heading_license': 'Лицензия',
                'readme_heading_contact': 'Контакты',
                'readme_install_clone_repo': 'Клонировать репозиторий',
                'readme_install_enter_directory': 'Перейти в директорию',
                'readme_install_dependencies': 'Установить зависимости',
                'readme_install_add_command': 'Добавить команду установки',
                'readme_usage_add_instructions': 'Добавить инструкции по использованию',
                'readme_contrib_intro': 'Вклад приветствуется. Пожалуйста:',
                'readme_contrib_step_1': 'Сделайте fork проекта',
                'readme_contrib_step_2': 'Создайте Feature Branch (`git checkout -b feature/AmazingFeature`)',
                'readme_contrib_step_3': "Сделайте commit изменений (`git commit -m 'Add some AmazingFeature'`)",
                'readme_contrib_step_4': 'Сделайте push ветки (`git push origin feature/AmazingFeature`)',
                'readme_contrib_step_5': 'Откройте Pull Request',
                'readme_license_line': 'Распространяется по лицензии {license}. Подробности в `LICENSE`.',
                'readme_contact_project_label': 'Проект',
                'readme_tree_no_folder': 'Папка не выбрана',
                'readme_stats_total_files': 'Всего файлов',
                'readme_stats_total_lines': 'Строк кода',
                'readme_stats_total_size': 'Общий размер',
                'readme_stats_top_languages': 'Основные языки',
                'readme_stats_lines_label': 'строк',
                'readme_save_success_prefix': 'README сохранен в',
                'readme_save_error_prefix': 'Не удалось сохранить',
                'readme_copy_success': 'README скопирован в буфер обмена',
                
                # Контекст
                'context_mark': 'Отметить/снять',
                'context_copy_path': 'Копировать путь',
                'context_open_location': 'Открыть расположение',
                
                # Недавние папки
                'tooltip_recent': 'Недавние папки',
                'btn_recent': 'Недавние',
                'clear_history': 'Очистить историю',
                'history_cleared': 'История очищена',
                
                # Горячие клавиши
                'shortcuts_subtitle': 'Справка по горячим клавишам',
                'shortcuts_section_general': 'Общие',
                'shortcuts_section_selection': 'Выбор',
                'shortcuts_section_navigation': 'Навигация',
                'shortcuts_section_zoom': 'Масштаб',
                'shortcuts_section_tools': 'Инструменты',
                'shortcuts_exit': 'Выйти из приложения',
                'shortcuts_refresh': 'Обновить дерево файлов',
                'shortcuts_mark': 'Отметить / снять файл',
                'shortcuts_clear': 'Очистить выбор',
                'shortcuts_mark_file': 'Отметить файл',
                'shortcuts_context': 'Открыть контекстное меню',
                'shortcuts_zoom_scroll': 'Масштаб колесом мыши',

                # О программе
                'about_description': 'Профессиональный проводник файлов с анализом кода и расширенными метриками.',
                'about_feat_selection': 'Умный выбор файлов',
                'about_feat_analysis': 'Анализ кода (TODO, дубликаты)',
                'about_feat_dashboard': 'Панель с метриками и графиками',
                'about_feat_readme': 'Автоматический генератор README',
                'about_feat_themes': '5 профессиональных тем',
                'about_feat_i18n': 'Поддержка нескольких языков',
                'about_feat_zoom': 'Масштабирование кода',
                'about_feat_export': 'Экспорт в различные форматы',

                # Основные кнопки
                'btn_clear': 'Очистить',
                'btn_todos': 'ЗД',
                'btn_duplicates': 'Дубликаты',
                'btn_limpmax': 'Очистка',
                'btn_shortcuts': 'Клавиши',
                'btn_about': 'О программе',
                'tooltip_clear': 'Очистить выбор (Ctrl+D)',
                'tooltip_todos': 'Найти TODO и ошибки',
                'tooltip_duplicates': 'Найти дублированный код',
                'tooltip_limpmax': 'Массовая очистка print и комментариев',
                'tooltip_shortcuts': 'Горячие клавиши',
                'tooltip_about': 'О Code Tools ++',
                
                # LimpMax
                'limpmax_title': 'Максимальная очистка',
                'limpmax_subtitle': 'Очистка print и комментариев с контролем по языку и безопасным выводом.',
                'limpmax_source': 'Источник',
                'limpmax_options': 'Параметры',
                'limpmax_output': 'Вывод',
                'limpmax_progress': 'Прогресс и результаты',
                'limpmax_scope_all': 'Обработать всю папку',
                'limpmax_scope_single': 'Обработать один файл',
                'limpmax_remove_prints': 'Удалить print / логи (Python, JS/TS, Java, C/C++, и др.)',
                'limpmax_remove_comments': 'Удалить комментарии по языку',
                'limpmax_remove_prints_label': 'Очистка логов',
                'limpmax_remove_comments_label': 'Очистка комментариев',
                'limpmax_remove_prints_desc': 'Удаляет операторы печати и логирования',
                'limpmax_remove_comments_desc': 'Удаляет однострочные и многострочные комментарии',
                'limpmax_output_mirror': 'Создать новую папку (зеркальная структура)',
                'limpmax_output_overwrite': 'Заменить исходные файлы',
                'limpmax_pick_file': 'Выбрать файл',
                'limpmax_pick_output': 'Выбрать папку вывода',
                'limpmax_eta': 'Оставшееся время',
                'limpmax_starting': 'Запуск LimpMax...',
                'limpmax_done': 'Процесс завершен',
                'limpmax_processed': 'Обработано файлов',
                'limpmax_copied': 'Скопировано файлов',
                'limpmax_modified': 'Изменено файлов',
                'limpmax_prints_removed': 'Удалено Print/Логов',
                'limpmax_comments_removed': 'Удалено комментариев',
                'limpmax_unsupported': 'Не поддерживается',
                'limpmax_time': 'Общее время',
                'limpmax_err_project': 'Выберите корректную папку проекта.',
                'limpmax_err_single': 'Выберите корректный файл.',
                'limpmax_err_option': 'Включите хотя бы одну опцию: print или комментарии.',
                'limpmax_err_output': 'Выберите папку вывода.',
                'limpmax_err_same_output': 'Вывод не может быть в той же папке проекта.',
                'limpmax_project_folder': 'Папка проекта',
                'limpmax_scope_label': 'Область обработки',
                'limpmax_single_file_label': 'Один файл',
                'limpmax_output_mode_label': 'Режим вывода',
                'limpmax_output_directory_label': 'Папка вывода',
                'limpmax_statistics': 'Статистика',

                # Окно О программе
                'about_app_tagline': 'Профессиональный анализ кода · Умный экспорт · Интерактивная панель',
                'about_section_features': 'Функции',
                'about_section_info': 'Информация',
                'about_feature_files': 'Управление\nфайлами',
                'about_feature_files_desc': 'Иерархическое дерево\nс множественным выбором',
                'about_feature_dashboard': 'Интерактивная\nпанель',
                'about_feature_dashboard_desc': 'Графики и статистика\nв реальном времени',
                'about_feature_search': 'Расширенный\nпоиск',
                'about_feature_search_desc': 'Мощные фильтры\nи регулярные выражения',
                'about_feature_export': 'Гибкий\nэкспорт',
                'about_feature_export_desc': 'Markdown, TXT,\nБуфер обмена, LLM',
                'about_feature_ai': 'Встроенный\nчат ИИ',
                'about_feature_ai_desc': 'Помощь ИИ с\nдинамическими моделями',
                'about_feature_limpmax': 'Умный\nLimpMax',
                'about_feature_limpmax_desc': 'Массовая очистка\nprint и комментариев',
                'about_feature_readme': 'Автоматический\nREADME',
                'about_feature_readme_desc': 'Профессиональное\nсоздание',
                'about_feature_themes': 'Настраиваемые\nтемы',
                'about_feature_themes_desc': '8+ профессиональных\nтем',
                'about_feature_todos': 'Анализ\nTODO',
                'about_feature_todos_desc': 'Сканирование\nкомментариев',
                'about_feature_duplicates': 'Обнаружение\nдубликатов',
                'about_feature_duplicates_desc': 'Идентичные\nфайлы',
                'about_feature_i18n': 'Несколько\nязыков',
                'about_feature_i18n_desc': 'Испанский\nи английский',
                'about_info_details': 'Детали',
                'about_info_contact': 'Контакты',
                'about_info_version': 'Версия',
                'about_info_developer': 'Разработчик',
                'about_info_python': 'Python',
                'about_info_framework': 'Фреймворк',
                'about_info_github': 'GitHub',
                'about_info_email': 'Email',
                'about_info_license': 'Лицензия',
                'about_info_languages': 'Языки',
                
                # Выбор темы
                'theme_window_title': 'Внешний вид',
                'theme_subtitle': 'Выберите цветовую схему интерфейса',
                'theme_active': 'Активная тема',
                'theme_badge_active': '• Активна',
                'theme_btn_apply': 'Применить',
                'theme_anim_title': 'Анимации',
                'theme_anim_bar': 'Анимированный фон главной панели',
                'theme_anim_enabled': 'Включено',
                'theme_anim_disabled': 'Выключено',
                
                # Выбор языка
                'lang_window_title': 'Язык / Language',
                'lang_subtitle': 'Выберите язык интерфейса',
                'lang_active': 'Активный язык',
                'lang_badge_active': '• Активен',
                'lang_btn_apply': 'Применить',
                
                # Чат с ИИ
                'btn_ai': 'ИИ',
                'tooltip_ai': 'Чат с ИИ (Ctrl+I)',
                'menu_ai_chat': 'Чат с ИИ',
                'ai_chat_title': 'Чат с ИИ',
                'ai_send': 'Отправить',
                'ai_clear': 'Очистить',
                'ai_analyze': 'Анализировать выбранное',
                'ai_fix_errors': 'Исправить ошибки',
                'ai_document': 'Документировать',
                'ai_optimize': 'Оптимизировать',
                'ai_explain': 'Объяснить',
                'ai_placeholder': 'Введите сообщение... (Shift+Enter для новой строки)',
                'ai_thinking': 'Думаю...',
                'ai_no_files': 'Нет выбранных файлов',
                'ai_error': 'Ошибка связи с ИИ',
                'ai_select_model': 'Модели',
                'ai_add_custom_model': '➕ Добавить пользовательскую модель...',
                'ai_model_changed': 'Модель изменена на:',
                'ai_select_model_subtitle': 'Выберите модель для использования в чате',
                'ai_model_active_badge': 'Активна',
                'ai_confirm': 'Подтвердить',
                'ai_delete_model_confirm': "Удалить модель '{name}'?",
                'ai_add_model_subtitle': 'Настройте пользовательскую модель OpenRouter',
                'ai_model_name_label': 'Название модели:',
                'ai_model_name_placeholder': 'Моя пользовательская модель',
                'ai_model_id_label': 'ID модели (напр: anthropic/claude-3-opus):',
                'ai_model_id_placeholder': 'anthropic/claude-3-opus',
                'ai_api_key_label': 'API ключ OpenRouter:',
                'ai_description_label': 'Описание (необязательно):',
                'ai_description_placeholder': 'Краткое описание',
                'ai_max_tokens_label': 'Максимум токенов:',
                'ai_custom_logo_label': 'Пользовательский логотип (PNG/GIF):',
                'ai_select_logo_title': 'Выбрать логотип',
                'ai_image_filetypes': 'Изображения',
                'ai_browse': 'Обзор',
                'ai_name_model_required': 'Требуются название и ID модели',
                'ai_add': 'Добавить',
                'ai_cancel': 'Отмена',
            }
}
    }
    
    def __init__(self, config_manager=None):
        self.config_manager = config_manager
        self.current_language = 'es'
        if config_manager:
            self.current_language = config_manager.get('language', 'es')
        self._observers = []
    
    def get_text(self, key):
        """Obtiene un texto traducido"""
        lang_data = self.LANGUAGES.get(self.current_language, self.LANGUAGES['es'])
        return lang_data['translations'].get(key, key)

    def set_language(self, lang_code):
        """Cambia el idioma de la interfaz"""
        if lang_code not in self.LANGUAGES:
            return
        
        self.current_language = lang_code
        
        # Guardar en configuración
        if self.config_manager:
            self.config_manager.set('language', lang_code)
        
        # Notificar a todos los observers
        self._notify_observers()

    def subscribe(self, callback):
        if callback not in self._observers:
            self._observers.append(callback)

    def unsubscribe(self, callback):
        if callback in self._observers:
            self._observers.remove(callback)

    def _notify_observers(self):
        dead = []
        for cb in self._observers:
            try:
                cb()
            except Exception:
                dead.append(cb)
        for cb in dead:
            self._observers.remove(cb)
    
    def get_available_languages(self):
        """Retorna lista de idiomas disponibles"""
        return [(code, data['name'], data['flag']) for code, data in self.LANGUAGES.items()]
    
    def get_current_language_name(self):
        """Retorna el nombre del idioma actual"""
        return self.LANGUAGES[self.current_language]['name']
